# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.IntegerField(max_length=10)),
                ('entree', models.CharField(max_length=255)),
                ('plat', models.CharField(max_length=200)),
                ('dessert', models.CharField(max_length=200)),
            ],
        ),
    ]
