# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='prix',
        ),
    ]
